"""add profile image and document fields

Revision ID: 9bc15c779634
Revises: db31b2d32dc7
Create Date: 2026-03-17 17:50:01.298578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc15c779634'
down_revision: Union[str, Sequence[str], None] = 'db31b2d32dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'document_url')
    op.drop_column('user_profiles', 'profile_image_url')
    # ### end Alembic commands ###
