"""add booking indexes

Revision ID: db31b2d32dc7
Revises: bb1f9163f057
Create Date: 2026-03-12 19:26:59.873237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db31b2d32dc7'
down_revision: Union[str, Sequence[str], None] = 'bb1f9163f057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_booking_user_date', 'bookings', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_index('idx_booking_user_date', table_name='bookings')
    # ### end Alembic commands ###
